---
- name: Preconfig
  hosts: ubuntus
  tasks:
    - name: Install Docker
      become: true
      block:
        - name: Add universal ubuntu packets
          apt_repository:
            repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
            state: present
        - name: Installing packets
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
            update_cache: yes
            cache_valid_time: 86400
          #ignore_errors: true NEED VPN!!
        - name: mkdir GPG key
          command: sudo mkdir -m 0755 -p /etc/apt/keyrings
        - name: Add Docker’s official GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            keyring: /etc/apt/keyrings/docker.gpg
            state: present
        - name: Add docker repos
          apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
            update-cache: yes
            filename: docker
          #ignore_errors: true NEED VPN!!
        - name: Rools
          command: chmod 777 /etc/apt/keyrings/docker.gpg
        - name: Installing Docker
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
        - name: Update and status Docker
          service:
            name: docker
            state: restarted
            enabled: yes
      become: yes
    - name: Install Docker-Compose
      block:
        - name: docker-compose last version
          uri:
            url: "https://api.github.com/repos/docker/compose/releases/latest"
            body_format: json
          register: dockercompose
        - name: Download Docker Compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ dockercompose.json.tag_name  }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
        - name: add usermode docker
          user:
            name: "{{ansible_user}}"
            groups: docker
            append: yes
        - name: Reboot servers
          reboot:
            reboot_timeout: 3600
      become: yes
